CREATE DATABASE veterinary;

CREATE TABLE IF NOT EXISTS public.owners
(
owner_id INT PRIMARY KEY,
ofirstname VARCHAR (50) NOT NULL,
olastname VARCHAR (50) NOT NULL,
address VARCHAR (50) NOT NULL,
phone VARCHAR (15) NOT NULL,
email VARCHAR (100) NOT NULL
);